
#include "sys.h"




#define SDO        HAL_GPIO_ReadPin(GPIOB,GPIO_PIN_2)  //SDO °´¼üPB2

#define CH_EN_SET  HAL_GPIO_WritePin(GPIOH,GPIO_PIN_12,GPIO_PIN_SET); 
#define CH_EN_RESET  HAL_GPIO_WritePin(GPIOH,GPIO_PIN_12,GPIO_PIN_RESET); 
#define CHCLK1_SET  HAL_GPIO_WritePin(GPIOH,GPIO_PIN_15,GPIO_PIN_SET); 
#define CHCLK1_RESET  HAL_GPIO_WritePin(GPIOH,GPIO_PIN_15,GPIO_PIN_RESET); 
#define CHCLK2_SET  HAL_GPIO_WritePin(GPIOI,GPIO_PIN_0,GPIO_PIN_SET); 
#define CHCLK2_RESET  HAL_GPIO_WritePin(GPIOI,GPIO_PIN_0,GPIO_PIN_RESET);
#define CHCLK3_SET  HAL_GPIO_WritePin(GPIOI,GPIO_PIN_1,GPIO_PIN_SET); 
#define CHCLK3_RESET  HAL_GPIO_WritePin(GPIOI,GPIO_PIN_1,GPIO_PIN_RESET);
#define CHCLK4_SET  HAL_GPIO_WritePin(GPIOI,GPIO_PIN_2,GPIO_PIN_SET); 
#define CHCLK4_RESET  HAL_GPIO_WritePin(GPIOI,GPIO_PIN_2,GPIO_PIN_RESET);
#define CHCLK5_SET  HAL_GPIO_WritePin(GPIOI,GPIO_PIN_3,GPIO_PIN_SET); 
#define CHCLK5_RESET  HAL_GPIO_WritePin(GPIOI,GPIO_PIN_3,GPIO_PIN_RESET);
#define CHCLK6_SET  HAL_GPIO_WritePin(GPIOA,GPIO_PIN_15,GPIO_PIN_SET); 
#define CHCLK6_RESET  HAL_GPIO_WritePin(GPIOA,GPIO_PIN_15,GPIO_PIN_RESET);
#define CHCLK7_SET  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_10,GPIO_PIN_SET); 
#define CHCLK7_RESET  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_10,GPIO_PIN_RESET);
#define CHCLK8_SET  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_11,GPIO_PIN_SET); 
#define CHCLK8_RESET  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_11,GPIO_PIN_RESET);
#define CHCLK9_SET  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_12,GPIO_PIN_SET); 
#define CHCLK9_RESET  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_12,GPIO_PIN_RESET);
#define CHCLK10_SET  HAL_GPIO_WritePin(GPIOD,GPIO_PIN_3,GPIO_PIN_SET); 
#define CHCLK10_RESET  HAL_GPIO_WritePin(GPIOD,GPIO_PIN_3,GPIO_PIN_RESET);
#define CHCLK11_SET  HAL_GPIO_WritePin(GPIOD,GPIO_PIN_4,GPIO_PIN_SET); 
#define CHCLK11_RESET  HAL_GPIO_WritePin(GPIOD,GPIO_PIN_4,GPIO_PIN_RESET);
#define CHCLK12_SET  HAL_GPIO_WritePin(GPIOD,GPIO_PIN_5,GPIO_PIN_SET); 
#define CHCLK12_RESET  HAL_GPIO_WritePin(GPIOD,GPIO_PIN_5,GPIO_PIN_RESET);
#define CHCLK13_SET  HAL_GPIO_WritePin(GPIOD,GPIO_PIN_6,GPIO_PIN_SET); 
#define CHCLK13_RESET  HAL_GPIO_WritePin(GPIOD,GPIO_PIN_6,GPIO_PIN_RESET);
#define CHCLK14_SET  HAL_GPIO_WritePin(GPIOD,GPIO_PIN_7,GPIO_PIN_SET); 
#define CHCLK14_RESET  HAL_GPIO_WritePin(GPIOD,GPIO_PIN_7,GPIO_PIN_RESET);
#define RELAYEN1_SET  HAL_GPIO_WritePin(GPIOB,GPIO_PIN_13,GPIO_PIN_SET); 
#define RELAYEN1_RESET  HAL_GPIO_WritePin(GPIOB,GPIO_PIN_13,GPIO_PIN_RESET);
#define RELAYEN2_SET  HAL_GPIO_WritePin(GPIOB,GPIO_PIN_14,GPIO_PIN_SET); 
#define RELAYEN2_RESET  HAL_GPIO_WritePin(GPIOB,GPIO_PIN_14,GPIO_PIN_RESET);
#define RELAYEN3_SET  HAL_GPIO_WritePin(GPIOB,GPIO_PIN_15,GPIO_PIN_SET); 
#define RELAYEN3_RESET  HAL_GPIO_WritePin(GPIOB,GPIO_PIN_15,GPIO_PIN_RESET);
#define RELAYEN4_SET  HAL_GPIO_WritePin(GPIOD,GPIO_PIN_11,GPIO_PIN_SET); 
#define RELAYEN4_RESET  HAL_GPIO_WritePin(GPIOD,GPIO_PIN_11,GPIO_PIN_RESET);
#define RELAYEN5_SET  HAL_GPIO_WritePin(GPIOD,GPIO_PIN_12,GPIO_PIN_SET); 
#define RELAYEN5_RESET  HAL_GPIO_WritePin(GPIOD,GPIO_PIN_12,GPIO_PIN_RESET);
#define RELAYEN6_SET  HAL_GPIO_WritePin(GPIOD,GPIO_PIN_13,GPIO_PIN_SET); 
#define RELAYEN6_RESET  HAL_GPIO_WritePin(GPIOD,GPIO_PIN_13,GPIO_PIN_RESET);
#define RELAYEN7_SET  HAL_GPIO_WritePin(GPIOG,GPIO_PIN_3,GPIO_PIN_SET); 
#define RELAYEN7_RESET  HAL_GPIO_WritePin(GPIOG,GPIO_PIN_3,GPIO_PIN_RESET);
#define RELAYEN8_SET  HAL_GPIO_WritePin(GPIOG,GPIO_PIN_6,GPIO_PIN_SET); 
#define RELAYEN8_RESET  HAL_GPIO_WritePin(GPIOG,GPIO_PIN_6,GPIO_PIN_RESET);
#define RELAYEN9_SET  HAL_GPIO_WritePin(GPIOG,GPIO_PIN_7,GPIO_PIN_SET); 
#define RELAYEN9_RESET  HAL_GPIO_WritePin(GPIOG,GPIO_PIN_7,GPIO_PIN_RESET);
#define RELAYEN10_SET  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_6,GPIO_PIN_SET); 
#define RELAYEN10_RESET  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_6,GPIO_PIN_RESET);
#define RELAYEN11_SET  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_7,GPIO_PIN_SET); 
#define RELAYEN11_RESET  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_7,GPIO_PIN_RESET);
#define RELAYEN12_SET  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_8,GPIO_PIN_SET); 
#define RELAYEN12_RESET  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_8,GPIO_PIN_RESET);
#define RELAYEN13_SET  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_9,GPIO_PIN_SET); 
#define RELAYEN13_RESET  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_9,GPIO_PIN_RESET);
#define RELAYEN14_SET  HAL_GPIO_WritePin(GPIOA,GPIO_PIN_8,GPIO_PIN_SET); 
#define RELAYEN14_RESET  HAL_GPIO_WritePin(GPIOA,GPIO_PIN_8,GPIO_PIN_RESET);
#define RELAYEN15_SET  HAL_GPIO_WritePin(GPIOH,GPIO_PIN_13,GPIO_PIN_SET); 
#define RELAYEN15_RESET  HAL_GPIO_WritePin(GPIOH,GPIO_PIN_13,GPIO_PIN_RESET);
#define RELAYEN16_SET  HAL_GPIO_WritePin(GPIOH,GPIO_PIN_14,GPIO_PIN_SET); 
#define RELAYEN16_RESET  HAL_GPIO_WritePin(GPIOH,GPIO_PIN_14,GPIO_PIN_RESET);

#define CTRLBUS1_SET  HAL_GPIO_WritePin(GPIOF,GPIO_PIN_8,GPIO_PIN_SET); 
#define CTRLBUS1_RESET  HAL_GPIO_WritePin(GPIOF,GPIO_PIN_8,GPIO_PIN_RESET); 
#define CTRLBUS2_SET  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_13,GPIO_PIN_SET); 
#define CTRLBUS2_RESET  HAL_GPIO_WritePin(GPIOC,GPIO_PIN_13,GPIO_PIN_RESET); 
#define CTRLBUS3_SET  HAL_GPIO_WritePin(GPIOI,GPIO_PIN_9,GPIO_PIN_SET); 
#define CTRLBUS3_RESET  HAL_GPIO_WritePin(GPIOI,GPIO_PIN_9,GPIO_PIN_RESET); 
#define CTRLBUS4_SET  HAL_GPIO_WritePin(GPIOI,GPIO_PIN_10,GPIO_PIN_SET); 
#define CTRLBUS4_RESET  HAL_GPIO_WritePin(GPIOI,GPIO_PIN_10,GPIO_PIN_RESET); 
#define CTRLBUS5_SET  HAL_GPIO_WritePin(GPIOI,GPIO_PIN_11,GPIO_PIN_SET); 
#define CTRLBUS5_RESET  HAL_GPIO_WritePin(GPIOI,GPIO_PIN_11,GPIO_PIN_RESET); 
#define CTRLBUS6_SET  HAL_GPIO_WritePin(GPIOF,GPIO_PIN_6,GPIO_PIN_SET); 
#define CTRLBUS6_RESET  HAL_GPIO_WritePin(GPIOF,GPIO_PIN_6,GPIO_PIN_RESET); 
#define CTRLBUS7_SET  HAL_GPIO_WritePin(GPIOF,GPIO_PIN_7,GPIO_PIN_SET); 
#define CTRLBUS7_RESET  HAL_GPIO_WritePin(GPIOF,GPIO_PIN_7,GPIO_PIN_RESET); 
#define CTRLBUS8_SET  HAL_GPIO_WritePin(GPIOI,GPIO_PIN_8,GPIO_PIN_SET); 
#define CTRLBUS8_RESET  HAL_GPIO_WritePin(GPIOI,GPIO_PIN_8,GPIO_PIN_RESET); 
#define CTRLBUS9_SET  HAL_GPIO_WritePin(GPIOE,GPIO_PIN_2,GPIO_PIN_SET); 
#define CTRLBUS9_RESET  HAL_GPIO_WritePin(GPIOE,GPIO_PIN_2,GPIO_PIN_RESET); 
#define CTRLBUS10_SET  HAL_GPIO_WritePin(GPIOE,GPIO_PIN_3,GPIO_PIN_SET); 
#define CTRLBUS10_RESET  HAL_GPIO_WritePin(GPIOE,GPIO_PIN_3,GPIO_PIN_RESET);
#define CTRLBUS11_SET  HAL_GPIO_WritePin(GPIOE,GPIO_PIN_4,GPIO_PIN_SET); 
#define CTRLBUS11_RESET  HAL_GPIO_WritePin(GPIOE,GPIO_PIN_4,GPIO_PIN_RESET);
#define CTRLBUS12_SET  HAL_GPIO_WritePin(GPIOE,GPIO_PIN_5,GPIO_PIN_SET); 
#define CTRLBUS12_RESET  HAL_GPIO_WritePin(GPIOE,GPIO_PIN_5,GPIO_PIN_RESET);
#define CTRLBUS13_SET  HAL_GPIO_WritePin(GPIOE,GPIO_PIN_6,GPIO_PIN_SET); 
#define CTRLBUS13_RESET  HAL_GPIO_WritePin(GPIOE,GPIO_PIN_6,GPIO_PIN_RESET);
#define CTRLBUS14_SET  HAL_GPIO_WritePin(GPIOF,GPIO_PIN_9,GPIO_PIN_SET); 
#define CTRLBUS14_RESET  HAL_GPIO_WritePin(GPIOF,GPIO_PIN_9,GPIO_PIN_RESET);
#define CTRLBUS15_SET  HAL_GPIO_WritePin(GPIOF,GPIO_PIN_10,GPIO_PIN_SET); 
#define CTRLBUS15_RESET  HAL_GPIO_WritePin(GPIOF,GPIO_PIN_10,GPIO_PIN_RESET);
#define CTRLBUS16_SET  HAL_GPIO_WritePin(GPIOA,GPIO_PIN_0,GPIO_PIN_SET); 
#define CTRLBUS16_RESET  HAL_GPIO_WritePin(GPIOA,GPIO_PIN_0,GPIO_PIN_RESET);
#define CTRLBUS17_SET  HAL_GPIO_WritePin(GPIOH,GPIO_PIN_2,GPIO_PIN_SET); 
#define CTRLBUS17_RESET  HAL_GPIO_WritePin(GPIOH,GPIO_PIN_2,GPIO_PIN_RESET);


#define FUSETEST1 PAout(5)   
#define FUSETEST2 PAout(6)   
#define FUSETEST3 PBout(0)   
#define FUSETEST4 PBout(1)   
#define FUSETEST5 PHout(6) 

#define FUSEDATA1 PHin(11)  
#define FUSEDATA2 PHin(10)
#define FUSEDATA3 PHin(9)
#define FUSEDATA4 PHin(8)
#define FUSEDATA5 PHin(7)



#define RESCTRL1  PIout(7)
#define RESCTRL2  PIout(6)
#define RESCTRL3  PIout(5)
#define RESCTRL4  PIout(4)
#define RESCTRL5  PBout(9)
#define RESCTRL6  PBout(8)
#define RESCTRL7  PBout(7)
#define RESCTRL8  PBout(6)
#define RESCTRL9  PBout(5)
#define RESCTRL10  PBout(4)
#define RESCTRL11  PBout(3)
#define RESCTRL12  PGout(12)
#define RESCTRL13  PGout(11)
#define RESCTRL14  PGout(10)
#define RESCTRL15  PGout(9)






void HV_FunRelay_Set(u8 uSetValue);
void fuhegz_process(void);



